# Copyright (c) 2021 aasaam software development group
version: '3'

services:
  nginx-access-log-syslog:
    container_name: nginx-access-log-syslog
    image: ghcr.io/aasaam/nginx-error-log-parser
    network_mode: host
    command: access-log --listen 127.0.0.1:5141 --tcp-server 127.0.0.1:6141
    restart: unless-stopped
  nginx-error-log-syslog:
    container_name: nginx-error-log-syslog
    image: ghcr.io/aasaam/nginx-error-log-parser
    network_mode: host
    command: error-log --listen 127.0.0.1:5140 --tcp-server 127.0.0.1:6140
    restart: unless-stopped
